### ISSUE TITLE
'Unexpected server response' using hassio by means of remote ssh invocation

### ISSUE THREAD

**Issue by mario-tux** [hassio-addons/addon-ssh#115]
# Problem/Motivation

I was used to trigger remote snapshots by means of ssh (followed by an rsync) to backup hassio configuration.
I used `ssh root@hassio 'hassio snapshots new --name automatic-snapshot'` to do this.
With recent updates (I guess of addon-ssh) it doens't work anymore:
```
$ ssh root@hassio 'hassio dns info'                                    
time="2020-01-06T12:21:23+01:00" level=error msg="Unexpected server response"
Unexpected server response
```

Other commands work well, it looks related to `hassio` command:
```
$ ssh root@hassio 'whoami'
root
```
## Expected behavior

Correct remote invocation

## Actual behavior

The reported error

## Steps to reproduce

Try the suggested commands.

## Proposed changes

I think it is related to the tmux usage. I also tried to disable it by means of the configuration option but it looks still used:
```
....
    "sftp": true,
    "compatibility_mode": false,
    "allow_agent_forwarding": false,
    "allow_remote_port_forwarding": false,
    "allow_tcp_forwarding": false
  },
  "zsh": false,
  "share_sessions": false,
  "packages": [],
  "init_commands": [],
  "web": {
    "ssl": true,
    "certfile": "fullchain.pem",
    "keyfile": "privkey.pem"
  }
```

**Comment by jleeuwes** [comment]
I'm experiencing this as well. The problem seems to be a missing `HASSIO_TOKEN`. That environment variable is set in `/etc/profile.d/hassio.sh` but that is not executed if ssh is executing a command instead of starting a shell.

It works if you make sure ssh sources that script:

`$ ssh root@hassiog 'source /etc/profile.d/hassio.sh ; hassio snapshots new'
slug: d07a4289`

But I consider this a workaround. To see how it could be solved in the addon code, I tried some things:

1. set the `HASSIO_TOKEN` using a `/etc/ssh/sshrc` script - doesn't work because that is apparently executed in a different shell so the variable doesn't stick
2. thought about putting it in `/root/ssh/environment` but `PermitUserEnvironment` is set to `no` in `/etc/ssh/sshd_config`, I assume for good reasons.

So input from someone more knowledgeable about ssh and/or from an addon maintainer would be welcome.

**Comment by jleeuwes** [comment]
Update for the workaround now the `hassio` command is replaced by the `ha` command: you should source `/etc/profile.d/homeassistant.sh` for the token instead of `/etc/profile.d/hassio.sh` (which now only sets a `PS1` variable).
