### ISSUE TITLE
Unable to use docker

### ISSUE THREAD

**Issue by hontas** [hassio-addons/addon-ssh#42]
# Problem/Motivation

Can't use access/use docker via ssh

## Expected behavior

To be able to run docker

## Actual behavior

![image](https://user-images.githubusercontent.com/1521113/47962953-99e27600-e024-11e8-9023-6be79430287e.png)

## Steps to reproduce

1. Install add-on
2. ssh in or use web terminal
3. try to access docker

## Proposed changes

Offer alternate solution or documentation on how to run docker (if that addon is not longer available)

## Versions
hass.io
Home Assistant: 0.81.5
SSH & Web Terminal: 3.5.0

**Comment by frenck** [comment]
Hi there @hontas!

The timing on your issue is unreal ;)

20 minutes ago, I made this commit:

https://github.com/hassio-addons/addon-ssh/commit/834c1223d9601d5d0a21531e2d1733dd2882f9ef

Summary: Currently, it is impossible to provide/offer this feature, due to recent changes in Hass.io. I'm awaiting updates to be implemented in the Home Assistant frontend, to make this possible again.

**Comment by hontas** [comment]
@frenck haha wow talk about fast resolution! 🥇 
ok - do you know of another way to run docker on hass.io - I want to setup deconz gateway for ZygBee integration and handily enough there is a container for that 😅

**Comment by frenck** [comment]
@hontas The Docker CLI is currently only available via the Hass.io debug SSH console:

<https://developers.home-assistant.io/docs/en/hassio_debugging.html>
