### ISSUE TITLE
Copying text in web-terminal fails

### ISSUE THREAD

**Issue by frog32** [hassio-addons/addon-ssh#78]
# Problem/Motivation

Selecting and copying text in the web-terminal does not work.

## Expected behavior

Being able to select text and copying it to use in a different program/window/tab that accepts text.

## Actual behavior

Selecting text does not work.

## Steps to reproduce

Try to copy paste text

## Proposed changes

If making text select-able it not possible a valid work around that other web based shells use it to copy text to clipboard as soon as it is selected.

**Comment by viotemp1** [comment]
I really miss this feature. Can this be solved? Any workaround/shortcuts?

**Comment by frenck** [comment]
Hold the modifier key while selecting (option on mac probably some other key on windows).
You'll notice the text selection becomes grey instead of yellow.

**Comment by nickdos** [comment]
I'm still having issues trying to copy text on a Mac. I've tried holding the **option** key down but it only changes the cursor to the crosshairs icon and selecting still shows a yellow background. 

I am able to use the **control** key but then I can only click on a single "word" and copy it - I cannot select more than one word because as soon as I start "dragging" the mouse, the background color changes from grey to yellow and I'm not able to copy anything. 

I've tried every combination of modifier keys and nothing works. Am I missing something?
